version: 2.1
executors:
  ruby-executor:
    docker:
      - image: cimg/ruby:3.1
      - image: cimg/postgres:13.4
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: test_db
    working_directory: ~/project
    environment:
      BUNDLE_PATH: vendor/bundle
jobs:
  test:
    executor: ruby-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-bundle-v1-{{ checksum "Gemfile.lock" }}
            - ruby-bundle-v1-
      - run:
          name: Install dependencies
          command: bundle install --jobs 4 --retry 3
      - save_cache:
          paths:
            - vendor/bundle
          key: ruby-bundle-v1-{{ checksum "Gemfile.lock" }}
      - run:
          name: Set up test database
          command: |
            cp config/database.yml.ci config/database.yml
            RAILS_ENV=test bundle exec rails db:create db:schema:load
      - run:
          name: Run tests
          command: bundle exec rspec
workflows:
  version: 2
  test:
    jobs:
      - test