version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1

jobs:
  test-ruby:
    docker:
      - image: cimg/ruby:3.2.2-node  # your app
      - image: cimg/postgres:14.8  # updated Postgres service
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@localhost:5432/test_db
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: |
            bundle exec rake db:create db:schema:load
      - run:
          name: rspec test
          command: bundle exec rspec

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'

workflows:
  build-and-test:
    jobs:
      - test-ruby
