default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: # Leave empty if no password is set
  host: localhost  # Or socket: /tmp/.s.PGSQL.5432 if you're using UNIX sockets

development:
  <<: *default
  database: geeki_development  # Adjust database name as needed

test:
  <<: *default
  database: geeki_test  # Adjust database name as needed

production:
  <<: *default
  database: geeki_production  # Adjust database name as needed
  username: <%= ENV['GEKI_PRODUCTION_DB_USERNAME'] %>
  password: <%= ENV['GEKI_PRODUCTION_DB_PASSWORD'] %>
  host: <%= ENV['GEKI_PRODUCTION_DB_HOST'] %>
  